"""
01. Classical Baselines for Time Series Forecasting
===================================================

Non-deep learning statistical baselines. These serve as the baseline benchmarks
for predicting time-series values.

Methods:
    * Naive / Persistence: Predicts the next step will be equal to the current step (y_t+1 = y_t).
    * Moving Average: Predicts the average of the last N historical steps.
    * ARIMA (Autoregressive Integrated Moving Average): Standard parametric statistical forecasting.

Run:
    python "01.baselines.py" --dataset jena --variant naive
    python "01.baselines.py" --dataset spy --variant ma
"""

import os
import numpy as np
import ts_common as mc


def run_naive(test_loader):
    """Predicts next step as the last step in the history window."""
    ys_true = []
    ys_pred = []
    for x, y in test_loader:
        # x shape is (batch, W, features). Last step of history window is index W-1.
        # The target feature is the target_idx (which is normalized temp/price).
        # We know target_idx is the target feature, and the loader contains already
        # normalized data.
        # But wait! The target is the last feature value of target_idx in the window.
        # The target feature is predicted from the target index in the last window step:
        # x is (batch, W, features). The target feature in the loader is processed
        # in ts_common.py to match target_idx. So let's extract the target feature at W-1.
        # Since the target feature value is at index W-1, let's find target_idx.
        # In ts_common, y_list is generated by taking the target_idx feature from the next step.
        # The corresponding current step is at index -1 in the window x.
        # But wait! Does the loader's x contain target_idx at index -1?
        # Yes, x[:, -1, target_idx] is the last historical observation of the target.
        # Wait, how do we know target_idx inside the script?
        # In ts_common.py, get_dataloaders returns (train_loader, test_loader, num_features, mean, std).
        # Ah! But it doesn't return target_idx directly.
        # Wait, let's look at ts_common.py implementation:
        # `return train_loader, test_loader, data.shape[1], mean[target_idx], std[target_idx]`
        # So the loader already has normalized X and y.
        # For jena, data has 3 features: [p, T, rho]. target_idx is 1 (T).
        # For spy, data has 1 feature: [Close]. target_idx is 0.
        # Wait, if we don't return target_idx, how does the model know which index to predict or look at?
        # Let's inspect ts_common.py.
        # Ah, for univariate/multivariate inputs, the last window step target value is at index 1 for jena, and 0 for spy.
        # Can we infer target_idx from num_features?
        # If num_features == 3 (jena), target_idx is 1. If num_features == 1 (spy), target_idx is 0.
        # Yes! Let's write a simple helper:
        # target_idx = 1 if num_features == 3 else 0.
        # Perfect!
        pass


def evaluate_baselines(test_loader, variant, num_features):
    target_idx = 1 if num_features == 3 else 0
    ys_true = []
    ys_pred = []

    for x, y in test_loader:
        # x shape is (batch, W, features)
        # y shape is (batch,)
        ys_true.append(y.numpy())
        if variant == "naive":
            # Predict y_t+1 as the last step in the history window: x[:, -1, target_idx]
            pred = x[:, -1, target_idx].numpy()
        elif variant == "ma":
            # Predict y_t+1 as the average of the history window: mean(x[:, :, target_idx])
            pred = x[:, :, target_idx].mean(dim=1).numpy()
        else:
            raise ValueError(f"Unknown variant: {variant}")
        ys_pred.append(pred)

    return np.concatenate(ys_true), np.concatenate(ys_pred)


def run_arima(train_loader, test_loader, num_features, limit):
    """Fits an ARIMA model on a subset of the training data and forecasts step-by-step."""
    target_idx = 1 if num_features == 3 else 0

    # Collect all train targets to fit ARIMA
    train_targets = []
    for _, y in train_loader:
        train_targets.append(y.numpy())
    train_seq = np.concatenate(train_targets)

    # Collect test targets
    test_targets = []
    for _, y in test_loader:
        test_targets.append(y.numpy())
    test_seq = np.concatenate(test_targets)

    # Limit train_seq size for ARIMA to prevent infinite run times in demos
    fit_len = min(1000, len(train_seq))
    train_seq = train_seq[-fit_len:]

    try:
        from statsmodels.tsa.arima.model import ARIMA
        print(f"Fitting ARIMA(2,1,0) on {len(train_seq)} points...")
        # Fit on training data
        model = ARIMA(train_seq, order=(2, 1, 0))
        model_fit = model.fit()

        # Step-by-step forecast on test data (rolling forecast or simple prediction)
        # To keep it fast, we can use the model to predict the next steps.
        # A simple one-step-ahead forecasting without manual retraining for every step:
        # We can use out-of-sample forecast or rolling prediction.
        # For simplicity and speed, we perform out-of-sample prediction using statsmodels.
        predictions = model_fit.forecast(steps=len(test_seq))
    except Exception as e:
        print(f"statsmodels ARIMA failed or not installed: {e}")
        print("Falling back to a simple Autoregressive baseline...")
        # Fallback: Simple AR(2) model fitted using Least Squares
        # y_t = c + phi1 * y_t-1 + phi2 * y_t-2
        X_ar, y_ar = [], []
        for i in range(2, len(train_seq)):
            X_ar.append([train_seq[i-1], train_seq[i-2]])
            y_ar.append(train_seq[i])
        X_ar = np.array(X_ar)
        y_ar = np.array(y_ar)
        # Solve least squares: w = (X^T X)^-1 X^T y
        w = np.linalg.pinv(X_ar.T @ X_ar) @ X_ar.T @ y_ar
        # Predict on test
        predictions = []
        # We use a rolling window of history to predict next step
        history = list(train_seq[-2:])
        for target in test_seq:
            pred = w[0] * history[-1] + w[1] * history[-2]
            predictions.append(pred)
            history.append(target)
        predictions = np.array(predictions)

    return test_seq, predictions


def main():
    p = mc.build_argparser("Classical Baselines for Time Series")
    # Override variant choices
    p.add_argument("--baseline-variant", type=str, default="naive", choices=["naive", "ma", "arima"],
                   help="override variant parameter")
    args = p.parse_args()

    # Determine variant
    variant = args.baseline_variant if args.baseline_variant != "naive" else (args.variant or "naive")
    if variant not in ["naive", "ma", "arima"]:
        variant = "naive"

    train_loader, test_loader, num_features, mean, std = mc.get_dataloaders(
        args.dataset, args.batch_size, args.limit
    )

    print(f"Running Baseline Variant: {variant.upper()} on {args.dataset.upper()} dataset")

    if variant in ["naive", "ma"]:
        y_true, y_pred = evaluate_baselines(test_loader, variant, num_features)
    elif variant == "arima":
        y_true, y_pred = run_arima(train_loader, test_loader, num_features, args.limit)

    mc.report(y_true, y_pred, mean, std, dataset_name=args.dataset,
              model_name=f"Baseline-{variant.upper()}",
              save_dir=None if args.no_figure else os.path.dirname(os.path.abspath(__file__)))


if __name__ == "__main__":
    main()
